export const theme = {
  text: {
    underline: "underline",
    italic: "italic",
    bold: "text-bold",
    strikethrough: "line-through",
    code: "editor-text-code",
  },
  hr: "border-t-2 border-gray-300 my-4",
  heading: {
    h1: "text-3xl font-bold my-2 border-b border-solid border-gray-300",
    h2: "text-2xl font-semibold my-2",
    h3: "text-xl font-medium my-2",
  },
  quote: "pl-4 border-l-4 border-gray-300 italic text-gray-600",
  list: {
    checklist: "relative mx-2 px-6 list-none outline-none block min-h-6 ",
    listitem: "relative",
    listitemUnchecked:
      "before:content-[''] outline-none before:absolute before:top-1/2 before:left-0 before:w-4 before:h-4 before:-translate-y-1/2 before:border before:border-gray-400 before:rounded before:bg-white",
    listitemChecked:
      "before:content-['✔'] outline-none line-through before:text-white before:text-xs before:flex before:items-center before:justify-center before:absolute before:top-1/2 before:left-0 before:w-4 before:h-4 before:-translate-y-1/2 before:bg-blue-600 before:border before:border-blue-600 before:rounded",
    nested: {
      listitem: "list-none",
    },
    ol: "list-decimal list-outside p-0 m-0",
    ul: "list-disc list-outside p-0 m-0",
  },
  code: "editor-code",
  codeHighlight: {
    atrule: "editor-tokenAttr",
    attr: "editor-tokenAttr",
    boolean: "editor-tokenProperty",
    builtin: "editor-tokenSelector",
    cdata: "editor-tokenComment",
    char: "editor-tokenSelector",
    class: "editor-tokenFunction",
    "class-name": "editor-tokenFunction",
    comment: "editor-tokenComment",
    constant: "editor-tokenProperty",
    deleted: "editor-tokenProperty",
    doctype: "editor-tokenComment",
    entity: "editor-tokenOperator",
    function: "editor-tokenFunction",
    important: "editor-tokenVariable",
    inserted: "editor-tokenSelector",
    keyword: "editor-tokenAttr",
    namespace: "editor-tokenVariable",
    number: "editor-tokenProperty",
    operator: "editor-tokenOperator",
    prolog: "editor-tokenComment",
    property: "editor-tokenProperty",
    punctuation: "editor-tokenPunctuation",
    regex: "editor-tokenVariable",
    selector: "editor-tokenSelector",
    string: "editor-tokenSelector",
    symbol: "editor-tokenProperty",
    tag: "editor-tokenProperty",
    url: "editor-tokenOperator",
    variable: "editor-tokenVariable",
  },
};
